FROM node:18-alpine
MAINTAINER Bart Oleszczyk <bart@primate.co.uk>

WORKDIR /kubik_interface_elements
RUN npm install -g npm
ADD ./package/package.json /kubik_interface_elements/package.json

RUN npm install
